packages/extension/package.json
packages/extension/src/app/App.tsx
packages/extension/src/app/screens/AccountList.tsx
packages/extension/src/app/screens/Connect.tsx
packages/extension/src/app/screens/Settings.tsx
packages/extension/src/app/states/RouterMachine.ts
packages/extension/src/app/utils/messaging.ts
packages/extension/src/background.ts
packages/extension/src/inpage.ts
packages/extension/webpack.config.js

https://argent.atlassian.net/browse/BLO-12
We need to be carefull not to expose the provider in window to every app. We should check how MetaMask does that as they had to change that specific behaviour.
Upon connecting the wallet from a dapp, the extension should open and request to connect to that specific dapp. The provider with the account, etc should only be injected if approved. The extension should keep a mapping of the approved dapps.
This MR also improves encryption/decryption when development mode is detected

feat: request connection

---

packages/extension/src/app/screens/Account.tsx
packages/extension/src/app/utils/tokens.ts
packages/extension/src/assets/erc20-tokens.json

Add a list of basic, "well known" ERC20 tokens in the extension's code to avoid showing an empty wallet when a user recovers an existing wallet.
Might need to check how often token details are cached and refreshed as this list grows in size.

Add a list of default tokens

---

packages/extension/src/ui/screens/DisclaimerScreen.tsx
packages/extension/src/ui/screens/ResetScreen.tsx

Makes the warning colour on these buttons more obviously "red".

[UPDATE] Change red warning button colour to Argent red.

---

packages/extension/src/background/index.ts
packages/extension/src/background/keys/l1.ts
packages/extension/src/background/selectedWallet.ts
packages/extension/src/shared/MessageType.ts
packages/extension/src/ui/states/RouterMachine.ts
packages/extension/src/ui/utils/messaging.ts

Recover the network from the background when reopening the wallet. This helps to stay in the same wallet after closing the extension ui

feat: recover network

---

packages/extension/src/ui/App.tsx
packages/extension/src/ui/components/Account/TokenList.tsx
packages/extension/src/ui/utils/swrCache.ts

this allows SWR to write the cache to localstorage and retrieve when asked. This will persist token balances between extension restarts and fetch the new balance in the background

feat: persist swr cache

---

packages/extension/src/ui/hooks/useStatus.ts

This fixes an issue where wallet deployment transactions where checked against the default provider instead of the wallet provider which could result in a network mismatch and therefore the wallet never shows as deployed

fix: mainnet tx status update

---

packages/extension/src/background/index.ts
packages/extension/src/background/trackTransactions.ts
packages/extension/src/shared/MessageType.ts
packages/extension/src/shared/transactions.model.ts
packages/extension/src/ui/App.tsx
packages/extension/src/ui/components/Account/AccountSubheader.tsx
packages/extension/src/ui/components/Account/EmptyWalletAlert.tsx
packages/extension/src/ui/components/Account/SectionHeader.tsx
packages/extension/src/ui/components/Account/TokenList.tsx
packages/extension/src/ui/components/Account/Transactions.tsx
packages/extension/src/ui/components/CopyTooltip.tsx
packages/extension/src/ui/components/Token.tsx
packages/extension/src/ui/screens/AccountScreen.tsx
packages/extension/src/ui/states/RouterMachine.ts
packages/extension/src/ui/states/actions.ts
packages/extension/src/ui/states/walletTransactions.ts
packages/extension/src/ui/utils/messaging.ts
packages/extension/src/ui/utils/wallet.ts

this PR adds support for pending transactions and shows them. 
It also adds some other improvements:
- Indicator is shown when token balances update in the background (swr)
- when signing something the extension shows a loading screen after approving until the transaction was broadcasted

feat: show pending transactions

---

packages/extension/src/background/index.ts
packages/extension/src/background/nonce.ts
packages/extension/src/background/notification.ts

Allows wallets to queue multiple transactions into one block, by increasing the nonce optimistically.
If one transaction fails all subsequent transactions will also fail (nonce mismatch)

feat: transaction queueing

---

packages/get-starknet/src/index.ts

This returns a window.starknet reference instead of a new object, so it can ignore potentual race conditions when the extension is slower than the DApp

fix: race condition in get-starknet

---

packages/extension/src/ui/components/Typography.tsx
packages/extension/src/ui/screens/SettingsScreen.tsx

Add a Help & Support section in settings page with links to Discord channel & Github issues

feat(settings): add support links to settings screen

---

packages/extension/src/background/trackTransactions.ts

by stopping the pinging after finallity is reached
We're using `ACCEPTED_ON_L2` or `REJECTED` as final for now, this may need to change to `ACCEPTED_ON_L1` in the future

feat: decrease load on sequencer

---

packages/extension/src/ui/hooks/useCustomNavigate.ts
packages/extension/src/ui/screens/WelcomeScreen.tsx

This is fixing issue #94 
On linux, when pressing "Recover Wallet" it will open the extension in a new browser tab.
It's not opening the recover screen but the welcome screen as in order to open that app at a given screen we need to change the main router

feat: open recover screen in a tab on linux

---

.github/workflows/dependabot.yml

it seems like you introduced some more restrictive github configs to the repo, therefore this change is needed

fix(ci): review deps prs automatically

---

packages/extension/src/ui/utils/tokens.ts

TODO: throw an error in starknet.js if input object has additional keys that cant be used as input arguments

fix: token balance fetching

---

packages/extension/src/ui/App.tsx
packages/extension/src/ui/screens/BackupDownloadScreen.tsx
packages/extension/src/ui/states/backupDownload.ts

- always show backup download screen whenever there's a change to the wallet (no more don't remind me again option)
- go directly to relevant screen after download
- typos

feat(ui): improve backup download flow

---

packages/dapp/package.json
packages/extension/package.json
packages/extension/src/background/index.ts
packages/extension/src/background/notification.ts
packages/extension/src/manifest.json
packages/extension/src/ui/hooks/useTransactionStatus.ts
packages/extension/src/ui/screens/AccountScreen.tsx
packages/get-starknet/package.json
yarn.lock

As StarkWare confirmed the PENDING state used by StarkNet is as final as ACCEPTED_ON_L2, therefore we should treat it the same to speed up (mainnet) transactions

feat: add PENDING state as final

---

packages/extension/src/background/index.ts
packages/extension/src/shared/MessageType.ts
packages/extension/src/ui/features/accounts/AccountListItem.tsx
packages/extension/src/ui/features/accounts/AccountListScreen.tsx
packages/extension/src/ui/features/accounts/UpgradeScreen.tsx
packages/extension/src/ui/features/accounts/accounts.state.ts
packages/extension/src/ui/features/actions/ActionScreen.tsx
packages/extension/src/ui/features/actions/FeeEstimation.tsx
packages/extension/src/ui/features/onboarding/NewWalletScreen.tsx
packages/extension/src/ui/features/onboarding/ResetScreen.tsx
packages/extension/src/ui/features/recovery/recovery.service.ts

failed for big transactions previously, but as starknet.js now returns the fee value in BigNumber it's fixed.

fix: fee estimation

---

packages/extension/src/background/networkMessaging.ts
packages/extension/src/background/recoveryMessaging.ts
packages/extension/src/background/wallet.ts
packages/extension/test/wallet.test.ts

if accountClassHash is provided for a network we use the new recovery mechanism. This allows only to recover new accounts and ignores any old accounts on that network.
If the network still has no accountClassHash we consider it pre cairo v0.9.0 and use the old recovery mechanism.
Pre cairo v0.9.0 should be removed as soon as devnet and mainnet support it.

feat: new recovery

---

packages/extension/src/ui/App.tsx
packages/extension/src/ui/AppErrorBoundaryFallback.tsx
packages/extension/src/ui/components/ErrorBoundary.tsx
packages/extension/src/ui/features/accountTokens/AccountTokens.tsx
packages/extension/src/ui/features/settings/SettingsScreen.tsx

Provides improved structuring for React Suspense and a high-level error boundary which provides a way for users to copy an error payload.
https://user-images.githubusercontent.com/175607/174849338-70fd5406-e7eb-48ea-9a86-e2f34b27487d.mov
Example payload
```
v4.1.4
Threw a manual exception
at Thrower (chrome-extension://ibeadmeiklhobeoiaolmnhmegnmhlggg/main.js:199894:42)
at Suspense
at ErrorBoundary (chrome-extension://ibeadmeiklhobeoiaolmnhmegnmhlggg/main.js:200470:47)
at InnerThemeProvider (chrome-extension://ibeadmeiklhobeoiaolmnhmegnmhlggg/main.js:89592:70)
at ThemeProvider (chrome-extension://ibeadmeiklhobeoiaolmnhmegnmhlggg/main.js:89120:5)
at ThemeProvider (chrome-extension://ibeadmeiklhobeoiaolmnhmegnmhlggg/main.js:89612:5)
at SWRConfig$1 …
```

feat: high level app error capture

---

packages/extension/src/ui/features/accountTokens/AccountTokens.tsx
packages/extension/src/ui/features/accountTokens/tokenPriceHooks.ts
packages/extension/src/ui/features/networks/useNetworks.ts

Adds a `useIsMainnet` hook and uses it to check if the user is both on mainnet, and has Argent services enabled, before fetching and displaying token / pricing data
Video shows a user initially on Testnet with only token values displayed, switches to Mainnet showing both token and currency values ($0.00...!), then disabling Argent services which causes only token values. to be shown on Mainnet.
https://user-images.githubusercontent.com/175607/176479547-3a587863-24b1-416e-af45-2501cfb73150.mov

fix: enable currency display only when on mainnet

---

packages/extension/src/ui/features/onboarding/ResetScreen.tsx

The current text in the reset screen is outdated. It mentions backup files and we’re not using them anymore.
The new text should be:
“If you reset your wallet, the only way to recover it is with your 12-word seed phrase. Make sure to back it up from the Argent X settings and save it somewhere securely before resetting the extension“

fix: update reset screen text

---

packages/extension/playwright.config.ts
packages/extension/src/ui/features/onboarding/LockScreen.tsx

when there are no other actions that need approval

fix: close popup after dapp extension unlock

---

packages/extension/src/ui/features/accounts/Account.ts

Fixes an issue where all accounts showed a status of 'deploying' for a split second as the deploy transaction was never removed on success.
Users will initially see the 'deploying' on first use, then the deploy transaction will be removed and 'deploying' will no longer show on subsequent launches.
Screen recording shows deploying accounts successfully, then repeatedly opening the extension and viewing the account list - 'deploying' no longer shown.
https://user-images.githubusercontent.com/175607/177519814-f9e6b1c8-9dd6-4727-a678-b9b68ba7ab9f.mov

fix: use consistent storage key for account deploy transaction

---

packages/extension/src/shared/api/constants.ts
packages/extension/src/shared/api/fetcher.ts
packages/extension/src/shared/tokenPrice.service.ts
packages/extension/src/shared/transactionReview.service.ts
packages/extension/src/shared/utils/fetcher.ts
packages/extension/src/ui/features/accountTokens/tokenPriceHooks.ts
packages/extension/src/ui/features/actions/transaction/useTransactionReview.ts
packages/extension/src/ui/index.tsx
packages/extension/src/ui/services/useArgentApiFetcher.ts
packages/extension/test/fetcher.test.ts

Adds functions and tests for adding the expected Argent headers to Argent API requests, including the currently selected network.
The core feature is a new hook `useArgentApiFetcher()` which returns an SWR-compatible `fetcher` which adds the expected headers to all requests, adjusting for network changes automatically.
The spec is that requests sent to Argent API services should include the following http headers:
`argent-version` - e.g. `4.1.7`
`argent-client` - `argent-x`
`argent-network` - e.g. `goerli` or `mainnet`

feat: add headers to argent api requests

---

packages/extension/src/ui/features/accounts/AccountColumn.tsx
packages/extension/src/ui/features/accounts/AccountListItem.tsx
packages/extension/src/ui/features/accounts/AccountListScreen.tsx
packages/extension/src/ui/features/accounts/AccountListScreenItem.tsx
packages/extension/src/ui/features/accounts/AccountRow.tsx
packages/extension/src/ui/features/accounts/accounts.service.ts
packages/storybook/src/features/accounts/AccountListItem.stories.tsx

Splits the visual part of AccountListItem into a separate stateless reusable component suitable for use in forthcoming features where user is picking from a list of accounts.

feat: refactor account list item into reusable component + storybooks

---

packages/dapp/package.json
packages/extension/package.json
packages/get-starknet/package.json
yarn.lock

Needed to update starknet.js to avoid feeEstimation errors. In Cairo 0.9.1, estimateFee response returns `overall_fee` instead of `amount`
Refer: https://github.com/0xs34n/starknet.js/pull/248

fix: update starknet.js to use new estimateFee response

---

packages/extension/src/shared/token/price.ts
packages/extension/src/ui/features/accountTokens/TokenScreen.tsx

Prettifies the values shown on the token detail screen using the same functions as in the list view.
After
Before

fix: dollar value on token detail screen

---

packages/extension/src/shared/token/price.ts
packages/extension/src/ui/features/accountTokens/SendTokenScreen.tsx
packages/extension/src/ui/features/accountTokens/tokenPriceHooks.ts
packages/extension/test/tokenPrice.test.ts

Adds extra functions that are better suited to taking user input value (e.g. '1.23') for conversion to currency. Open to ideas for better naming :)
Uses these functions to fix an issue in the send screen where the dollar value was not updating.
https://user-images.githubusercontent.com/175607/180770078-61a08c11-52cb-4df5-88e5-427b64e09f6a.mov

fix: dollar value of user input

---

packages/extension/src/shared/utils/number.ts
packages/extension/src/ui/components/InputText.tsx
packages/extension/src/ui/features/actions/transaction/ERC20TransferTransactionDetails.tsx
packages/extension/test/InputText.test.ts
packages/extension/test/tokenPrice.test.ts

Adds function and tests for checking numeric input, default restricted to max 16 decimals (longer than this causes other libraries e.g. ethers to fail)

fix: restrict input decimal length to default 16

---

packages/extension/src/shared/network/index.ts
packages/extension/src/shared/network/storage.ts
packages/extension/src/ui/features/networks/useNetworks.ts
packages/extension/src/ui/features/settings/NetworkSettingsFormScreen.tsx
packages/extension/src/ui/features/settings/NetworkSettingsScreen.tsx

Adjustments so that default custom networks are non-readonly and can therefore be removed
Add a 'reset' feature so users can restore defaults
We accept that users who upgrade will lose 'localhost' from their custom networks however they can restore it using the 'reset' feature
https://user-images.githubusercontent.com/175607/180965121-0ad70b9f-fd1d-42f7-a8bb-28791cf23e1a.mov

fix: user can remove non-readonly default network

---

packages/extension/src/ui/features/accountTokens/tokenPriceHooks.ts
packages/extension/src/ui/services/swr.ts
packages/extension/test/swr.test.tsx

Adds adjustments and tests to the 'polling' behaviour for token and price endpoints.
New behaviour
* Default revalidate on mount (otherwise you may never see fresh prices)
* Dedupe requests to poll interval (otherwise 'mount' behaviour above causes multiple requests)
Previous behaviour
* Lack of 'dedupe' could cause multiple requests when remounting components, e.g. switching accounts

fix: adjust polling behaviour

---

packages/extension/src/ui/features/accountTokens/AccountTokens.tsx
packages/extension/src/ui/features/accountTokens/tokens.state.ts

* don’t show the token list until the account is deployed
* update the check for 429 error - was only checking the error key `status` but looks like it comes through as `errorCode` here

fix: don't show tokens until account is deployed

---

packages/extension/src/background/index.ts
packages/extension/src/background/transactions/badgeText.ts
packages/extension/src/shared/actionQueue/store.ts
packages/extension/src/shared/browser/badgeText.ts
packages/extension/src/ui/features/accounts/AccountContainer.tsx
packages/extension/src/ui/features/accounts/AccountFooter.tsx

This shows the count of pending transactions of the currently selected account with a new badge in the 'Activity' tab and changes to the count logic in the extension icon (which previously showed a count of pending actions). The extension icon will update in the background.

feat: pending transactions badge

---

packages/sessions/README.md

There should actually 2 be differents object:
- `Signer` and `ec` come from starknet.js and provides the command create a session key and sign transactions
- `sessionRequest: SessionRequest` and `createSession` are defined in @argent/x-sessions and are used to generate the signedSession

update session with RequestSession

---

packages/extension/src/ui/features/accounts/AccountListItem.tsx

Update the account list styling to cause long names to truncate

fix: improve display of long account name in list

---

packages/sessions/src/utils.ts

It could be beneficial you export `Policy` especially because (1) you reference it in the doc and export requestSession and (2) you might want to change it and it would help if I do not redefine it. Obviously this configuration might also be on purpose to force using `preparePolicy`

export the Policy interface

---

packages/extension/src/ui/components/InputText.tsx
packages/extension/src/ui/features/accountNfts/SendNftScreen.tsx
packages/extension/src/ui/features/accountTokens/SendTokenScreen.tsx
packages/extension/src/ui/features/settings/AddressbookAddOrEditScreen.tsx
packages/extension/src/ui/services/addresses.ts
packages/extension/test/InputText.test.ts
packages/extension/test/addresses.test.ts

Adds optional restriction to input that only allow user to type or paste a `0x0abc...` address. Adds additional changes and tests for address function(s) which were throwing on invalid input.

fix: address field crash

---

packages/extension/src/background/miscellaneousMessaging.ts
packages/extension/src/background/notification.ts
packages/extension/src/background/transactions/onupdate/index.ts
packages/extension/src/background/transactions/onupdate/nonce.ts
packages/extension/src/background/transactions/onupdate/notifications.ts
packages/extension/src/background/transactions/store.ts

Triggers notification on known transaction status change instead of load. This fixes an issue where restoring a wallet would trigger a notification for every single transaction.

fix: notification trigger

---

packages/storybook/.storybook/decorators.tsx
packages/storybook/.storybook/preview-head.html
packages/storybook/.storybook/preview.ts

Improve Storybook config to use extension dimensions without breaking Docs layout

fix(storybook): broken docs layout

---

packages/extension/src/ui/features/actions/connectDapp/DappIcon.tsx
packages/extension/src/ui/features/actions/transaction/fields/DappContractField.tsx
packages/storybook/src/ui/components/DappContractField.stories.tsx

Fixes css for dapp contract field with very long title, adds storybook and stories

fix: crushed icon when title is long

---

packages/extension/src/ui/features/accountActivity/transform/explorerTransaction/__test__/__fixtures__/explorer-transactions/goerli-alpha/erc20-transfer-with-sequencer-event.json
packages/extension/src/ui/features/accountActivity/transform/explorerTransaction/__test__/__fixtures__/explorer-transactions/goerli-alpha/index.ts
packages/extension/src/ui/features/accountActivity/transform/explorerTransaction/__test__/fingerprintExplorerTransaction.test.ts
packages/extension/src/ui/features/accountActivity/transform/explorerTransaction/__test__/transformExplorerTransaction.test.ts
packages/extension/src/ui/features/accountActivity/transform/explorerTransaction/fingerprintExplorerTransaction.ts

Adds a check for unexpected events that are gas fee transfers to sequencer.

fix(ui): check and ignore sequencer transfers

---

packages/extension/src/ui/features/accountActivity/transform/explorerTransaction/__test__/fingerprintExplorerTransaction.test.ts
packages/extension/src/ui/features/accountActivity/transform/explorerTransaction/fingerprintExplorerTransaction.ts

Ignore additional sequencer fee `Transfer` event after `transaction_executed` which was introduced in 0.10. This additional event breaks transaction identification, previous fix was tied to goerli but this should be network agnostic.

fix: mainnet rich transactions

---

packages/extension/src/ui/features/funding/FundingQrCodeScreen.tsx
packages/extension/src/ui/services/addresses.ts

Adds a button which copies the checksummed address on click. Intercepts mouseup on the address field to select the whole text. Intercepts copy event to replace spaced address with checksummed.
https://user-images.githubusercontent.com/175607/194035093-09267903-7134-4962-83d1-9c6218d070f6.mov

fix: copy address

---

packages/storybook/src/ui/components/Input.stories.tsx
packages/storybook/src/ui/components/TextArea.stories.tsx
packages/storybook/src/ui/components/TextAreaDeprecated.stories.tsx
packages/ui/src/components/Input.tsx
packages/ui/src/components/Textarea.tsx
packages/ui/src/components/index.ts
packages/ui/src/theme/index.ts
packages/ui/src/theme/shadows.ts
packages/ui/src/theme/spacing.ts

Adds primitive solid Input and Textarea (lowercase 'a' in chakra) following design system

feat: primitive styled inputs

---

packages/extension/src/ui/features/accounts/AccountListScreen.tsx
packages/extension/src/ui/features/accounts/AccountScreen.tsx

Fixes an issue where the new account list has a close button that may cause user to see an empty screen. This state will not be possible once the full UI implementation work is completed.

fix: don't show empty screen when closing account list

---

packages/extension/e2e/switchNetwork.test.ts
packages/extension/src/shared/wallet.service.ts
packages/extension/src/ui/features/accounts/switchAccount.ts

when switching network, keeps the current account if it exist on the network
otherwise, open the first account

feat: remember last selected account on network

---

packages/extension/src/ui/App.tsx
packages/ui/src/theme/SetDarkMode.tsx
packages/ui/src/theme/index.tsx

This PR reworks the method used to enforce 'dark' mode in the extension to use 'official' Chakra hooks

fix: rework enforced dark mode

---

packages/extension/src/shared/network/provider.ts

This PR makes an adjustment so that calls to `getProvider()` are memoized and create a single instance of `SequencerProvider()` for each `baseUrl`, rather than creating a new instance of `SequencerProvider()` each time it is called.

chore: memoize creation of provider for each baseUrl

---

packages/extension/src/assets/default-tokens.json

Updates localhost devnet token address for breaking change in devnet v0.4.0
https://github.com/Shard-Labs/starknet-devnet/releases/tag/v0.4.0

fix: update devnet eth address for v0.4.0

---

packages/extension/src/shared/avatarImage.ts
packages/extension/src/ui/features/accountTokens/TokenIcon.tsx
packages/extension/src/ui/features/accounts/accounts.service.ts
packages/extension/src/ui/features/actions/connectDapp/useDappDisplayAttributes.ts

removes the network requests (and dependence on) `eu.ui-avatars.com`
better late than never

feat: use new locally generated avatars

---

packages/extension/src/ui/AppRoutes.tsx

Fixes an issue where a duplicate route was preventing the account list UI from displaying correctly with a sticky navigation bar.
After (navigation bar is sticky)
---
Before (navigation bar scrolls off screen)

fix: account list header is sticky

---

packages/extension/src/ui/components/ErrorBoundaryFallbackWithCopyError.tsx
packages/storybook/src/ui/components/ErrorBoundary.stories.tsx

Adds a toast success message when clicking the submit button, and adds a story demonstrating this
https://user-images.githubusercontent.com/175607/203747891-11e44e5a-6e2c-46bc-9df1-764d09075312.mov

feat: show success message on submitting error

---

packages/extension/src/ui/features/accountTokens/tokens.service.ts

Use Promise.allSettled so a single failure doesn't break whole list

BLO-581 - fix(ui): improve handling of individual token errors

---

packages/extension/src/background/accountDeploy.ts
packages/extension/src/background/accountMessaging.ts
packages/extension/src/background/actionHandlers.ts
packages/extension/src/background/transactions/transactionExecution.ts
packages/extension/src/background/transactions/transactionMessaging.ts
packages/extension/src/shared/analytics.ts

Fixes 2 issues:
- is unavailable for deployment error from sequencer in case a wallet is already deployed
- tracking of `deployAccount`

fix: multi deploy and analytics

---

packages/extension/src/ui/features/accounts/AccountContainer.tsx
packages/extension/src/ui/features/accounts/AccountScreen.tsx
packages/extension/src/ui/features/settings/SettingsScreen.tsx
packages/ui/src/components/NavigationBar.tsx
packages/ui/src/components/NavigationContainer.tsx
packages/ui/src/hooks/index.ts
packages/ui/src/hooks/useScroll.ts
packages/ui/src/hooks/useScrollRestoration.ts

In preparation for animated transition work, this PR adds opt-in scroll restoration to `NavigationContainer` and a hook for using it independently. To simplify this initial implementation, scroll is restored only on 'pop' (back) navigation.

BLO-605 - feat(ui): opt-in scroll restoration

---

packages/extension/src/background/actionHandlers.ts
packages/extension/src/background/networkMessaging.ts

Resolves #1615 
- This feature allows to change network with StarknetChainId enum on starknet.js

feat: allow the usage of chainId as hex for network switching

---

package.json

Builds failing due to bundlesize of 4mb
- update bundlesize to 5mb

fix: update bundlesize for current code size

---

packages/ui/scripts/generate-icons.ts

Running the gen:icons script would generate source files with inconsistent white space and line endings, so you would always end up with source code changes - even if the icon artwork is unchanged
- remove empty line at beginning of generated file
- use LF instead of old-school CRLF for line endings

fix: script reproduces exact icon source code

---

.github/workflows/test.yml

`Add artifacts download link for each PR using gitHub actions`
`changed test gitHub workflow`

chore: Build should be available for each PR as an artifact

---

packages/extension/e2e/src/page-objects/Activity.ts
packages/extension/e2e/src/page-objects/ExtensionPage.ts
packages/extension/e2e/src/specs/sendMaxTokens.spec.ts
packages/extension/e2e/src/test.ts
packages/extension/src/ui/features/accountTokens/SendTokenScreen.tsx
packages/extension/src/ui/features/accountTokens/TokenListItem.tsx
packages/extension/src/ui/features/accountTokens/TokenListItemContainer.tsx
packages/extension/src/ui/features/accountTokens/TokenScreen.tsx
packages/extension/src/ui/features/accountTokens/useMaxFeeForTransfer.ts
packages/extension/src/ui/features/accountTokens/useTokenBalanceForAccount.ts
packages/extension/src/ui/services/swr.ts
packages/ui/src/theme/spacing.ts

Token balances are not synchronised across screens and may sometimes show outdated values
- use single balanceOf swr hook for individual token balances to share cached value
- use refreshInterval instead of polling helper so values are revalidated on mount
- use inline 'skeleton' loading state for initial token balances

BLO-707 fix: token balances are synchronised

---

packages/guardian/src/services/GuardianSigner.ts

Tx simulation sends version and nonce as hex which don't get converted in current code
- convert to BN before converting to decimal

fix: allow version and nonce as hex

---

packages/extension/src/background/wallet.ts

Follow up of the previous PR applied to a particular issue: no account found but the user is allowed to progress through the onboarding flow.

[BLO-715] Extension bricked after restoring from recovery phrase with no deployed accounts

---

packages/extension/src/background/wallet.ts

Just a follow up fix of a previous PR. The error was being thrown for all seedphrase recoveries, even valid ones.

fix error being thrown on all recoveries

---

packages/extension/src/shared/settings/store.ts
packages/extension/src/shared/settings/types.ts
packages/extension/src/ui/features/accountEdit/AccountEditScreen.tsx
packages/extension/src/ui/features/accountEdit/AccountImplementationScreen.tsx
packages/extension/src/ui/features/settings/ExperimentalSettings.tsx
packages/extension/src/ui/features/shield/ShieldBaseFinishScreen.tsx
packages/extension/src/ui/features/shield/ShieldBaseOTPScreen.tsx
packages/extension/src/ui/features/shield/useAccountGuardian.ts
packages/extension/src/ui/features/shield/useArgentShieldEnabled.ts
packages/storybook/src/ui/components/CellStack.stories.tsx
packages/ui/src/components/CellStack.tsx

Adds a user setting to enable access to the 2FA UI. Note this is a separate layer on top of the feature flag and does not replace it.
- add experimental setting
- add checks for 2FA accounts before disable
- update UI

BLO-713 feat: 2fa settings

---

packages/extension/src/ui/features/accountActivity/AccountActivity.tsx
packages/extension/src/ui/features/accountActivity/PendingTransactions.tsx
packages/extension/src/ui/features/accountActivity/TransactionDetail.tsx
packages/extension/src/ui/features/accountActivity/TransactionListItem.tsx
packages/extension/src/ui/features/accountActivity/useTransactionFees.test.ts
packages/extension/src/ui/features/accountActivity/useTransactionFees.ts

`There were already network fees but they were purely relying on backend data. Now there's a fallback with starknet js that way the fees should always be visible for a completed transaction`
Added a custom hook to get the fees + test on it

[BLO-729] Activity view should display fee cost

---

packages/extension/src/background/transactions/fees/store.ts
packages/extension/src/background/transactions/transactionExecution.ts
packages/extension/src/background/transactions/transactionMessaging.ts
packages/extension/src/shared/analytics.ts

`We are basically memoizing the fee computation so that the same fee is applied in the estimate screen and in the transaction execution itself`

[BLO-664] Apply estimated maxFee when sending a transaction

---

packages/extension/src/background/shieldMessaging.ts
packages/extension/src/shared/messages/ShieldMessage.ts
packages/extension/src/shared/shield/backend/account.ts
packages/extension/src/shared/shield/register.ts
packages/extension/src/ui/features/shield/ShieldBaseOTPScreen.tsx

`Move requests from the UI to the background process.`
- Create a few new messages to pass the data around
- Add validation on fetcher error messages so we can safely display custom error messages

[BLO-766] Move 2FA <-> backend requests into background process

---

packages/extension/src/shared/messages/index.ts

Firefox is not able to handle functions in the message bus
Usually we do not send (and never expect) functions, but sometimes it's easier to pass a superset of the message to the function. This PR will make sure that functions in this superset will get ignored

fix(firefox): change implementation

---

packages/extension/src/ui/App.tsx
packages/extension/src/ui/features/shield/useArgentShieldEnabled.ts

Users who recover and have accounts with 2FA enabled, we should automatically enable the 2FA feature in settings for them
- add a check for accounts with 2FA and enable the 2FA setting if > 0 and setting is not enabled

BLO-777 feat: 2fa auto-enable shield

---

packages/extension/src/ui/features/accountEdit/AccountEditScreen.tsx
packages/extension/src/ui/features/accounts/accountTransactions.state.ts
packages/extension/src/ui/features/shield/ShieldAccountFinishScreen.tsx
packages/extension/src/ui/features/shield/ShieldBaseFinishScreen.tsx
packages/extension/src/ui/features/shield/ui/ShieldHeader.tsx
packages/extension/src/ui/features/shield/usePendingChangingGuardian.ts

Fixes an issue where the 'live' state of 2FA on account was not in sync with on-chain state and would show momentarily in the wrong state
- add a hook to react to both tx and on-chain state, resolving when on-chain state is updated
- also display tx failure

BLO-739 fix: 2fa state transition

---

packages/extension/src/ui/features/actions/transaction/ApproveTransactionScreen/ConfirmScreen.tsx

[BLO-744] Transaction confirm button should be orange on hover

---

packages/extension/src/ui/features/accountTokens/ExportPrivateKeyScreen.tsx

`Remove some disabling that was preventing the export of private key (private key is still protected by same validations)`

[BLO-732] Export private key - Export button always disabled

---

packages/extension/src/shared/transactions.ts

API responses sometimes contain hex strings for names which end up in the UI
- filter hex strings when creating display title

BLO-788 fix: hex names

---

packages/extension/src/ui/features/accountActivity/AccountActivity.tsx
packages/extension/src/ui/features/accountActivity/AccountActivityContainer.tsx
packages/extension/src/ui/features/accountActivity/PendingTransactions.tsx
packages/extension/src/ui/features/accountActivity/TransactionListErrorItem.tsx
packages/extension/src/ui/features/accountActivity/useArgentExplorer.ts

'Activity' screen not resilient to unexpected conditions of network / backend / individual tx parsing
- refactor to remove suspense for more granular error handling, ignore network failures
- error boundary on each individual row for localised parse errors
- improve screen error boundary to allow reporting

BLO-835 fix: activity errors

---

packages/extension/src/background/transactions/sources/voyager.ts
packages/extension/src/ui/features/accounts/accounts.state.ts
packages/extension/src/ui/features/recovery/recovery.service.ts
packages/extension/src/ui/features/settings/NetworkSettingsScreen.tsx
packages/extension/src/ui/features/settings/validateRemoveNetwork.ts

Users are able to reset networks while a custom network and account is selected
- additional checks for network selection and existence when resetting and recovering

BLO-813 fix: guards and checks for deleting custom networks

---

packages/extension/src/ui/features/accountEdit/AccountImplementationScreen.tsx

Target account not used for implementation change
- use target account and select it before implementation change

BLO-772 fix: use target account for implementation change

---

packages/extension/src/ui/features/lock/LockScreen.tsx
packages/extension/src/ui/features/lock/PasswordForm.tsx

`Tx error is displayed on login screen`
- refactored lock screen and form to use local state instead of app state (had registered the tx error)
- tested locally with ionel too (to replicate, send max currency to another account and make another transaction while the first one is still pending)

BLO-780 fix: remove appstate for managing errors in lock screen

---

packages/extension/src/ui/features/accountNfts/aspect.service.ts
packages/extension/src/ui/features/actions/transaction/ApproveTransactionScreen/BalanceChangeOverview/NftDetails.tsx
packages/extension/src/ui/features/actions/transaction/ApproveTransactionScreen/DappHeader/TransactionIcon/NftTransactionIcon.tsx
packages/extension/src/ui/features/actions/transaction/ApproveTransactionScreen/DappHeader/TransactionTitle.tsx
packages/extension/src/ui/features/actions/transaction/ApproveTransactionScreen/index.tsx
packages/extension/src/ui/features/actions/transaction/useTransactionSimulation.ts

- also handle loading states
Add polling on Transaction Simulation to always get the latest data. Also added better loading state handling

fix: add transaction simulation polling

---

.github/workflows/chromatic.yml
.github/workflows/dependabot.yml
.github/workflows/gh-pages.yml
.github/workflows/release.yml
.github/workflows/test.yml
.yarnrc
.yarnrc.yml
Contributing.md
Readme.md
package.json
packages/get-starknet/package.json
packages/guardian/package.json
packages/multicall/package.json
packages/sessions/package.json
packages/stack-router/package.json
packages/swap/package.json
packages/ui/package.json
yarn.lock

BLO-804
Introduces @lavamoat/allow-scripts to avoid npm packages to run scripts.
It contains a whitelist of scripts that can run, and unifies postinstall and prepare scripts into one setup script.
When setting up we should run `yarn setup` instead of `yarn` or `yarn install`. 
This is described in https://github.com/LavaMoat/LavaMoat/blob/main/packages/allow-scripts/README.md#improving-your-workflow

feat: introduce @lavamoat/allow-scripts

---

packages/extension/src/ui/features/send/SendScreen.tsx

`Only show the NFTs tab if he user has NFTs`

[BLO-767] Hide NFTs tab in send screen if user has none

---

packages/extension/src/ui/features/shield/ShieldAccountEmailScreen.tsx
packages/extension/src/ui/features/shield/ShieldBaseEmailScreen.tsx
packages/extension/src/ui/features/shield/WithArgentShieldVerified.tsx
packages/storybook/src/features/shield/ShieldBaseEmailScreen.stories.tsx

User should see a different email prompt if 2FA is active
- add additional prompt driven by account state
- add storybook

BLO-785 feat: change email prompt if 2FA is active

---

Deployment.md

Due to the introduction of `@lavamoat/allow-scripts` the versioning and release process has changed slightly.

docs: deployment

---

package.json
packages/extension/package.json

Release was tagged before manifest changes
- lerna updates package versions but don't commit or add tag
- add updated files, commit and tag after manifest changes

BLO-872 fix: release tags

---

packages/extension/src/shared/shield/GuardianSignerArgentX.ts
packages/guardian/src/services/GuardianSigner.ts

Wrong endpoint used for personal sign and unexpected payload
- pass expected flag in subclass method
- add address padding to request

BLO-873 fix: 2fa personal message signing

---

packages/extension/src/shared/shield/GuardianSignerArgentX.ts
packages/guardian/src/services/GuardianSigner.ts

Can use endpoint to check token expiry (excluding for removal)
- change code to use be endpoint to check token expiry

BLO-838 chore: use endpoint to determine token expiry

---

packages/extension/src/shared/transactionSimulation/types.ts
packages/extension/src/ui/features/actions/transaction/useTransactionSimulatedData.ts

Adapt to backend changes for ERC721. Backend now responds with `tokenId` for ERC721 and `value` for ERC20.
- Build tokens based on value or tokenId

hotfix: adapt to backend simulation api

---

packages/extension/src/background/activeTabs.ts
packages/extension/src/background/preAuthorizationMessaging.ts

- add tab so it can receive messages

BLO-887 fix: add tab

---

packages/extension/src/ui/features/accounts/upgrade.service.ts
packages/extension/src/ui/features/settings/DappConnection.tsx
packages/extension/src/ui/features/settings/DappConnectionsSettingsScreen.tsx
packages/storybook/src/features/settings/DappConnectionsSettings.stories.tsx

`Some long dapp names not displaying correcty`
- use ui package for dapp list
- truncate long names
- add storybook
`
Before

BLO-879 feat: use ui package for dapp screen

---

packages/extension/src/shared/analytics.ts
packages/extension/src/shared/shield/validation.test.ts
packages/extension/src/shared/shield/validation.ts
packages/extension/src/ui/features/onboarding/OnboardingDisclaimerScreen.tsx
packages/extension/src/ui/features/onboarding/OnboardingFinishScreen.tsx
packages/extension/src/ui/features/onboarding/OnboardingPasswordScreen.tsx
packages/extension/src/ui/features/onboarding/OnboardingRestoreSeed.tsx
packages/extension/src/ui/features/onboarding/OnboardingStartScreen.tsx
packages/extension/src/ui/features/shield/ShieldAccountActionScreen.tsx
packages/extension/src/ui/features/shield/ShieldAccountEmailScreen.tsx
packages/extension/src/ui/features/shield/ShieldAccountOTPScreen.tsx
packages/extension/src/ui/features/shield/ShieldAccountStartScreen.tsx
packages/extension/src/ui/features/shield/ShieldBaseFinishScreen.tsx
packages/extension/src/ui/features/shield/ShieldValidationErrorScreen.tsx
packages/extension/src/ui/features/shield/escape/EscapeGuardian.tsx
packages/extension/src/ui/features/shield/escape/EscapeSigner.tsx
packages/extension/src/ui/features/shield/escape/EscapeWarningScreen.tsx
packages/extension/src/ui/features/shield/useAccountGuardian.ts
packages/extension/src/ui/features/shield/useShieldTracking.ts
packages/extension/src/ui/features/shield/useShieldVerifiedEmail.ts
packages/extension/src/ui/services/analytics.ts

Adds analytics to 2fa
- add analytics

BLO-875 feat: 2fa analytics

---

.github/workflows/release.yml

Enable 2fa in CI builds
- add flags to enable 2fa on mainnet in CI

chore: ci flags for 2fa

---

packages/extension/src/background/devnet/declareAccounts.ts
packages/extension/src/background/wallet.ts

This PR speeds up e2e-tests by computing class hash for Proxy and Account Contracts and checking if it's already declared. This is way faster than declaring contracts everytime.
- Compute and check if class exists before declaring on Localhost

feat: speedup e2e

---

.github/workflows/gh-pages.yml
.github/workflows/test-e2e.yml
.github/workflows/test.yml

Update action flow:
- Only dependabot.yml should run if action triggered by DependaBot
Note: dependabot.yml already run all the tests.
Action flows

fix: only run dependabot flow for action triggered by dependabot

---

packages/extension/src/shared/account/details/getImplementation.ts
packages/extension/src/ui/features/accountEdit/AccountEditScreen.tsx

Check if an account can have 2fa enabled before showing the option
- add hook to check if account is current implementation

BLO-904 feat: check if account can have 2fa enabled

---

packages/extension/src/shared/account/details/getImplementation.ts
packages/extension/src/ui/features/accountEdit/AccountEditScreen.tsx
packages/extension/src/ui/features/shield/ShieldAccountNotDeployed.tsx
packages/extension/src/ui/features/shield/ShieldAccountStartScreen.tsx

2fa should check for both undeployed + upgradable accounts when activating
- refactor check
- remove unused hook

BLO-922 fix: 2fa check

---

packages/extension/src/ui/services/backgroundAccounts.ts

Users unable to switch network on FireFox (due to DataCloneError on FF)
- coerce stored account to the expected sparse object

BLO-892 hotfix: ensure sparse account object

---

packages/extension/src/ui/features/actions/feeEstimation/CombinedFeeEstimation.tsx
packages/extension/src/ui/features/actions/feeEstimation/FeeEstimation.tsx
packages/extension/src/ui/features/actions/feeEstimation/ui/CopyErrorIcon.tsx
packages/extension/src/ui/features/actions/feeEstimation/ui/FeeEstimationBox.tsx
packages/extension/src/ui/features/actions/feeEstimation/ui/FeeEstimationText.tsx
packages/extension/src/ui/features/actions/feeEstimation/ui/InsufficientFundsAccordion.tsx
packages/extension/src/ui/features/actions/feeEstimation/ui/TransactionFailureAccordion.tsx
packages/storybook/src/features/actions/transaction/CombinedFeeEstimation.stories.tsx
packages/storybook/src/features/actions/transaction/FeeEstimationText.stories.tsx
packages/storybook/src/features/actions/transaction/__fixtures__/fees/combinedFeeEstimationFixtures.ts
packages/storybook/src/ui/components/Accordion.stories.tsx
packages/storybook/src/ui/components/Button.stories.tsx
packages/ui/src/components/Accordion.tsx

Fee error states should match designs
- add accordion theme with error style
- implement for error states in fee estimation

BLO-930 chore: fee error ui

---

packages/extension/src/shared/shield/backend/time.ts
packages/extension/src/shared/shield/jwt.ts

Use server time when creating jwt
- add time endpoint
- determine time skew with server
- calculate expected backend time using skew

BLO-934 fix: 2fa time skew
