argentlabs/argent-x

Readme.md
Adds an `Install from source` section to the readme.
=> update readme to include `Install from source` section

packages/extension/package.json, packages/get-starknet/package.json, yarn.lock
=> chore: update to starknet.js 2.0.1

packages/extension/package.json, packages/extension/src/abi/ERC20.json, packages/extension/src/assets/erc20-tokens.json, packages/extension/src/ui/App.tsx, packages/extension/src/ui/states/RouterMachine.ts, packages/extension/src/ui/utils/tokens.ts, packages/get-starknet/package.json, packages/playground/package.json, packages/playground/src/services/token.service.ts, yarn.lock
This PR implements the new ERC20 as defined in openzeppelins repo, with shortstring symbol and name aswell as uint256 for token balances.
(!) The contract abi parsing needs to be revisited at some point to make it easier
=> feat: support new erc20

packages/extension/src/assets/erc20-tokens.json, packages/extension/src/ui/App.tsx, packages/extension/src/ui/components/Account/AccountList.tsx, packages/extension/src/ui/components/Account/EmptyWalletAlert.tsx, packages/extension/src/ui/components/Account/TokenList.tsx, packages/extension/src/ui/screens/AccountScreen.tsx, packages/extension/src/ui/screens/AddTokenScreen.tsx, packages/extension/src/ui/states/RouterMachine.ts, packages/extension/src/ui/utils/tokens.ts, packages/playground/src/components/TokenDapp.tsx, packages/playground/src/services/token.service.ts, packages/playground/src/services/wallet.service.ts
Various refactors to accommodate for the fact that tokens are network-specific
=> feat: multi network tokens

packages/extension/package.json, packages/extension/src/ui/components/Account/TokenList.tsx, packages/playground/next-env.d.ts, yarn.lock
uses swr for token balance fetching
`stale-while-refetch` is a web standard which allows to fetch data in the background while showing the stale data until fetching is done.
closes #61
=> feat: use swr for token fetch

yarn.lock
Reverts argentlabs/argent-x#88
=> Revert "chore(deps): bump starknet from 2.3.1 to 2.5.0"

packages/extension/package.json, packages/extension/src/background/actionQueue.ts, packages/extension/src/background/index.ts, packages/extension/src/inpage/index.ts, packages/extension/src/shared/MessageType.ts, packages/extension/src/ui/App.tsx, packages/extension/src/ui/screens/ApproveSignScreen.tsx, packages/extension/src/ui/screens/ConfirmScreen.tsx, packages/extension/src/ui/states/RouterMachine.ts, packages/get-starknet/package.json, packages/playground/package.json, packages/playground/src/components/TokenDapp.tsx, packages/playground/src/services/wallet.service.ts, packages/playground/src/styles/Home.module.css, yarn.lock
adds offchain message signing to argent-x
=> feat: message signing

packages/extension/webpack.config.js
Improve on the unbearably slow (~1 sec) reaction time after clicking on the toolbar icon and waiting for the popup to appear by not loading unnecessary code in this window.
=> chore(webpack): performance improvement

packages/extension/src/ui/utils/tokens.ts
=> fix(ui): fix decimals parsing bug

packages/extension/src/background/index.ts, packages/extension/src/inpage/index.ts, packages/extension/src/inpage/model.ts, packages/extension/src/shared/MessageType.ts, packages/extension/src/shared/actionQueue.ts, packages/extension/src/shared/token.model.ts, packages/extension/src/ui/App.tsx, packages/extension/src/ui/screens/AddTokenScreen.tsx, packages/get-starknet/src/extension.model.ts, packages/get-starknet/src/index.ts, packages/playground/src/components/TokenDapp.tsx, packages/playground/src/services/wallet.service.ts, packages/playground/src/styles/globals.css
As a DApp Developer I want to be able to add my token to the wallet extension programmatically.
=> feat: add token from dapp

packages/extension/src/background/index.ts, packages/extension/src/background/keys/l1.ts, packages/extension/src/shared/MessageType.ts, packages/extension/src/ui/screens/SettingsScreen.tsx
Added a new button in the setting page to allow users to manually save the backup file whenever they want.
=> feat(key-file): added option to manually save the backup file.

packages/extension/src/background/activeTabs.ts, packages/extension/src/background/index.ts, packages/extension/src/inpage/index.ts, packages/extension/tsconfig.json
https://user-images.githubusercontent.com/6831124/150134892-95ad855e-7e44-4740-86d8-faa09d897012.mp4
=> feat: allow multiple tabs to connect at the same time

.github/dependabot.yml
from daily to weekly on Sundays
=> chore: update Dependabot schedule

packages/extension/src/inpage/index.ts, packages/extension/src/inpage/model.ts, packages/get-starknet/src/extension.model.ts
=> feat: expose version to dapp

packages/extension/src/background/keys/l1.ts
dont cache results when the password was wrong
=> fix: password issue

packages/extension/src/inpage/index.ts, packages/extension/src/inpage/model.ts, packages/get-starknet/src/extension.model.ts, packages/get-starknet/src/index.ts, packages/playground/src/pages/index.tsx, packages/playground/src/services/wallet.service.ts
=> feat: allow dapp to check if whitelisted

packages/extension/src/ui/screens/AddTokenScreen.tsx
dont block user from rejecting a token add action when loading
=> fix: always allow action rejection

packages/extension/src/background/index.ts, packages/extension/src/background/notification.ts, packages/extension/src/ui/hooks/useStatus.ts, packages/extension/src/ui/states/tokens.ts, packages/extension/src/ui/utils/tokens.ts
With this PR token balances fallback to their previous values in case they can't get fetched
=> feat: failsave token balances

packages/extension/src/ui/states/tokens.ts
I introduced a bug in the quickfix from today. This fix will make sure the balance stays if fetching fails
=> fix: token merge logic

packages/playground/src/pages/index.tsx
All DeFi apps I use work this way, might as well do the same in our playground
=> feat(playground): autoconnect dapp if preauthorized

packages/extension/src/background/nonce.ts
This PR fixes an issue that occured when queueing transactions
=> fix: queued transactions

packages/extension/src/background/actionQueue.ts, packages/extension/src/background/index.ts, packages/extension/src/background/openUi.ts
this also fixes a bug with popup window detection that was introduced with the router switch
=> fix(action-queue): switch to inmemory for performance

packages/extension/src/background/whitelist.ts, packages/extension/src/ui/App.tsx, packages/extension/src/ui/components/Account/Dapp.tsx, packages/extension/src/ui/components/Account/DappsList.tsx, packages/extension/src/ui/routes.ts, packages/extension/src/ui/screens/DappsScreen.tsx, packages/extension/src/ui/screens/SettingsScreen.tsx
Closes #90 
https://user-images.githubusercontent.com/3721291/153302295-23c8f088-49d0-4cc0-b063-b9c56c56498b.mp4
=> feat: view and remove dapp connections

packages/extension/src/background/index.ts, packages/extension/src/shared/MessageType.ts, packages/extension/src/ui/Wallet.ts, packages/extension/src/ui/screens/ErrorScreen.tsx
Avoid confusion about localhost network, with explanations about potential conflict on port 5000 on macOS.
=> feat(ui): show better error message when deploying

packages/extension/src/ui/hooks/useStatus.ts
=> fix: setIsDeployed true after account deployed

packages/extension/src/ui/screens/HideTokenScreen.tsx
Implements https://github.com/argentlabs/argent-x/issues/293
https://user-images.githubusercontent.com/19926174/155840471-eb232766-6c8c-4ac8-a3c3-2aab9ed02d32.mov
=> refactor(ui): reuse ConfirmScreen in HideTokenScreen

packages/extension/src/background/index.ts, packages/extension/src/background/keys/keyDerivation.ts
This allows transaction queuing
=> feat(background): add local nonce copy back

packages/extension/src/shared/networks.ts
ArgentAccount on mainnet: 0x05f28c66afd8a6799ddbe1933bce2c144625031aafa881fa38fa830790eff204
=> adding deployment address of ArgentAccount on mainnet

packages/dapp/package.json, packages/extension/package.json, packages/extension/src/background/index.ts, packages/extension/src/inpage/index.ts, packages/extension/src/inpage/legacy.ts, packages/extension/src/inpage/model.ts, packages/extension/src/shared/MessageType.ts, packages/extension/src/shared/actionQueue.ts, packages/extension/src/ui/screens/ActionScreen.tsx, packages/extension/src/ui/screens/ApproveTransactionScreen.tsx, packages/get-starknet/package.json, packages/get-starknet/src/extension.model.ts, yarn.lock
Support `starknet.js` v2 code in dapps for backwards compatibility and a smoother migration
=> feat(extension): support legacy transactions

packages/extension/src/ui/screens/AddTokenScreen.tsx, packages/extension/src/ui/utils/tokens.ts
this was caused by the starknet v3 update.
It's very likely that we need to touch this again once contracts interface v3 is merged
=> fix: token details fetch

packages/dapp/abi/ERC20.json, packages/dapp/package.json, packages/dapp/src/services/token.service.ts, packages/dapp/src/services/wallet.service.ts, packages/extension/package.json, packages/extension/src/inpage/index.ts, packages/extension/src/ui/utils/tokens.ts, packages/get-starknet/package.json, yarn.lock
merge after https://github.com/0xs34n/starknet.js/pull/138 gets merged, released and the dependency of argent updated
=> fix: use new contract interface

Deployment.md, packages/extension/package.json
Please test before merging. Keep open until the next release was done using this (rebased) branch.
=> fix(release): automatic version bump for manifest

docs/Upgrade_v3.md
Improve description of loading unpacked unzipped folder
=> doc: update process

packages/dapp/package.json, packages/extension/package.json, packages/get-starknet/package.json, scripts/update-starknet-js.sh, yarn.lock
was fixed in latest starknet.js@next release
=> fix: fee estimate

.github/workflows/release.yml, packages/extension/src/inpage/index.ts
=> fix: inject more reliably

packages/extension/package.json, packages/extension/src/ui/screens/BackupRecoveryScreen.tsx, yarn.lock
=> chore: update react-dropzone

packages/extension/src/background/index.ts, packages/extension/src/background/tokens.ts, packages/extension/src/inpage/index.ts, packages/extension/src/inpage/model.ts, packages/extension/src/shared/MessageType.ts, packages/extension/src/shared/actionQueue.ts, packages/extension/src/shared/json.ts, packages/extension/src/shared/token.model.ts, packages/extension/src/shared/token.ts, packages/extension/src/ui/App.tsx, packages/extension/src/ui/components/Account/TokenList.tsx, packages/extension/src/ui/screens/ActionScreen.tsx, packages/extension/src/ui/screens/AddTokenScreen.tsx, packages/extension/src/ui/screens/HideTokenScreen.tsx, packages/extension/src/ui/states/tokens.ts, packages/extension/src/ui/utils/messaging.ts, packages/extension/src/ui/utils/swrCache.ts, packages/extension/src/ui/utils/tokens.ts
this allows to do checks on the token list without opening the UI
eg: checking if a token already exists in case a dapp wants to add one
=> feat: store tokens in background

.github/dependabot.yml
this will run friday morning, our usual release day
=> ci: run dependabot fridays

packages/extension/src/assets/default-tokens.json
=> feat: add mainnet eth

packages/extension/src/background/accounts.ts, packages/extension/src/background/index.ts, packages/extension/src/background/trackTransactions.ts
Less "callback-based programming" style
=> refactor(background): make entrypoint bit more understandable

packages/extension/src/inpage/index.ts, packages/extension/src/inpage/inpage.model.ts, packages/extension/src/inpage/starknetWindowObject.ts
=> Add `chainId` field to StarknetWindowObject and implement `chainChanged` event listener

packages/extension/src/background/index.ts, packages/extension/src/background/wallet.ts
=> fix(background): wallet autolock memory leak

packages/extension/src/ui/features/accountTokens/TokenScreen.tsx
=> UI token balance overflow

packages/extension/src/background/customNetworks.ts, packages/extension/src/ui/features/actions/AddNetworkScreen.tsx
fixes the dapp methods to add and switch chains
=> fix: chain dapp api

packages/extension/src/background/price.ts, packages/extension/src/background/transactions/transactionExecution.ts, packages/extension/src/background/transactions/transactions.ts, packages/extension/src/shared/analytics.ts, packages/extension/src/ui/features/accountTokens/tokens.state.ts, packages/extension/src/ui/features/accounts/AccountScreen.tsx, packages/extension/src/ui/features/actions/ApproveTransactionScreen.tsx, packages/extension/src/ui/features/actions/FeeEstimation.tsx
and more, see individual commits
=> fix: transaction queuing

packages/extension/src/background/wallet.ts
covers the case where a user does the migration from v3 to v4 multiple times
(more for us devs than for the actual user)
=> fix: check for new wallet existence

packages/extension/src/shared/call.ts, packages/extension/src/ui/features/accountTokens/TokenIcon.tsx, packages/extension/src/ui/features/accounts/ProfilePicture.tsx, packages/extension/src/ui/features/actions/ApproveTransactionScreen.tsx, packages/extension/src/ui/features/actions/ConfirmScreen.tsx, packages/extension/src/ui/features/actions/TransactionsList.tsx, packages/extension/test/call.test.ts
Adds client-side transaction review fallback screen with additional specific UI for ERC20 transfer
=> feat: transaction review fallback screen

packages/extension/src/ui/features/accountTokens/ExportPrivateKeyScreen.tsx
https://user-images.githubusercontent.com/50968441/174578800-ec80f58c-433c-4f4f-b0bb-5c9088477781.mov
=> feat: add private key copy feedback

packages/extension/src/ui/App.tsx
bugfix: multiple global style override not working in production build - refactor to use single global style with props
=> bugfix: broken fullscreen mode

packages/extension/src/ui/features/accountTokens/AccountSubheader.tsx, packages/extension/src/ui/features/accountTokens/AccountTokens.tsx
fix: pass `account` argument so that tokens balances are fetched
=> fix: account total balance

packages/extension/src/ui/AppRoutes.tsx, packages/extension/src/ui/components/PrivacyStatement.tsx, packages/extension/src/ui/features/onboarding/DisclaimerScreen.tsx, packages/extension/src/ui/features/onboarding/PrivacyStatementScreen.tsx, packages/extension/src/ui/features/onboarding/StickyArgentFooter.tsx, packages/extension/src/ui/features/onboarding/WelcomeScreen.tsx, packages/extension/src/ui/features/settings/SettingsScreen.tsx, packages/extension/src/ui/routes.ts
=> feat: add privacy statement

packages/dapp/package.json, packages/extension/package.json, packages/get-starknet/package.json, yarn.lock
=> feat: update starknetjs

packages/extension/src/ui/features/accountNfts/NftScreen.tsx, packages/extension/src/ui/features/accountNfts/aspect.model.ts, packages/extension/src/ui/features/accountNfts/aspect.service.ts
Sorry about this but I forgot to add the new API fields. It should display the images properly now.
=> fix: use new api fields

packages/extension/.env.example, packages/extension/src/shared/tokenPrice.service.ts, packages/extension/src/ui/index.tsx, packages/extension/test/__mocks__/argent-api-prices-invalid.mock.json, packages/extension/test/__mocks__/argent-api-prices.mock.json, packages/extension/test/__mocks__/argent-api-tokens-invalid.mock.json, packages/extension/test/__mocks__/argent-api-tokens.mock.json, packages/extension/test/__mocks__/tokens-with-balance.mock.json, packages/extension/test/tokenPrice.test.ts, packages/extension/test/tokenPriceHooks.test.tsx, packages/extension/test/utils/number.test.ts
* updates snapshots from staging API
* updates tests to use updated data shape
* adds tests to show expected behaviour with invalid or missing data
* removes `REACT_APP_` prefix from dotenv var
=> feat: update token / currency tests and features for production API 

packages/storybook/.storybook/main.ts, packages/storybook/tsconfig.json
Fixes `yarn storybook` which was broken after recent dependabot changes
=> fix: storybook config

packages/extension/src/ui/features/actions/transaction/DefaultTransactionDetails.tsx
allows devs to copy the contract address of the contract they are interacting with on the transaction approve screen
=> feat(approve-tx): copy contract address

packages/extension/src/assets/default-tokens.json
from https://github.com/starkware-libs/starkgate-frontend/blob/dev/src/config/tokens.js
=> feat(default-tokens): add new mainnet tokens

packages/extension/src/background/accountMessaging.ts, packages/extension/src/background/keys/keyDerivation.ts, packages/extension/src/background/transactions/onupdate/notifications.ts, packages/extension/src/background/wallet.ts, packages/extension/src/shared/messages/AccountMessage.ts, packages/extension/src/ui/components/Button.tsx, packages/extension/src/ui/components/ErrorBoundaryFallbackWithCopyError.tsx, packages/extension/src/ui/features/accountTokens/AccountSubheader.tsx, packages/extension/src/ui/features/accountTokens/AccountTokens.tsx, packages/extension/src/ui/features/accountTokens/useAccountStatus.ts, packages/extension/src/ui/features/accounts/Account.ts, packages/extension/src/ui/features/accounts/AccountListScreen.tsx, packages/extension/src/ui/features/actions/ErrorScreen.tsx, packages/extension/src/ui/features/onboarding/NewWalletScreen.tsx, packages/extension/src/ui/services/backgroundAccounts.ts
- Fixes some uninitialised checks that occasionally throw
- Contextual state and error when creating new wallet
- Contextual state and error when adding a new account
- Contextual state, error and ability to retry when deploy transaction doesn't complete satisfactorily
https://user-images.githubusercontent.com/175607/180208624-584a16f0-fa38-4ab1-91e2-5a6ce9d45d39.mov
https://user-images.githubusercontent.com/175607/180208634-7f73c0c6-445c-453b-88f4-15f2334d3603.mov
https://user-images.githubusercontent.com/175607/180208642-2414dac5-1c80-42cf-8766-8ba77ddac462.mov
=> fix: wallet and account deploy errors

packages/extension/src/ui/features/accountTokens/tokens.state.ts
Adds a special case to the token list to suppress frequent errors (429 only at the moment). When the error matches this code, swr will retry again using default exponential backoff and the error will not propagate to parent.
=> fix: suppress 429 error in token list

packages/extension/src/shared/token/utils.ts, packages/extension/src/ui/AppRoutes.tsx, packages/extension/src/ui/features/accountActivity/AccountActivity.tsx, packages/extension/src/ui/features/accountActivity/PendingTransactions.tsx, packages/extension/src/ui/features/accountActivity/TransactionDetailScreen.tsx, packages/extension/src/ui/features/accountActivity/TransactionListItem.tsx, packages/extension/src/ui/features/accountActivity/useActivity.ts, packages/extension/src/ui/features/accountTokens/AccountTokens.tsx, packages/extension/src/ui/features/accounts/AccountScreen.tsx, packages/extension/src/ui/features/actions/transaction/DefaultTransactionDetails.tsx, packages/extension/src/ui/features/actions/transaction/TransactionDetails.tsx, packages/extension/src/ui/features/actions/transaction/TransactionsList.tsx, packages/extension/src/ui/features/actions/transaction/fields/TokenField.tsx, packages/storybook/.storybook/main.ts, packages/storybook/src/features/accounts/AccountActivity.stories.tsx, packages/storybook/src/features/accounts/PendingTransactions.stories.tsx, packages/storybook/src/features/accounts/TransactionDetail.stories.tsx, packages/storybook/src/features/accounts/TransactionListItem.stories.tsx, packages/storybook/src/features/accounts/__fixtures__/transactions-pending.json, packages/storybook/src/features/accounts/__fixtures__/transactions.json, packages/storybook/src/features/actions/transaction/tokensByNetwork.ts
Refactors and renames some 'Transaction' related components to prepare the way for adding rich transaction feeds. Captures existing behaviour with fixtures in Storybook
=> chore: refactor transaction ui

docs/Upgrade_v3.md
=> Fix: typos

packages/extension/src/assets/known-dapps.json, packages/extension/src/shared/knownDapps.ts, packages/extension/src/ui/features/accountActivity/transform/explorerTransaction/__test__/transformExplorerTransaction.test.ts, packages/extension/src/ui/features/accountActivity/transform/transaction/__test__/transformTransaction.test.ts, packages/extension/src/ui/features/actions/connectDapp/useDappDisplayAttributes.ts
Adds a few more dapps and implements an optional fallback icon
=> feat: add known dapps

packages/extension/src/ui/features/actions/ApproveTransactionScreen.tsx
=> fix: remove stray console.log

packages/extension/src/shared/network/schema.ts, packages/extension/src/shared/utils/object.ts, packages/extension/src/ui/features/settings/NetworkSettingsFormScreen.tsx, packages/extension/src/ui/features/settings/useYupValidationResolver.ts, packages/extension/test/networkSchema.test.ts, packages/extension/test/object.test.ts
Adds deep form object value clean before validation, updated schema for required value inside optional object, adds tests
=> fix: unable to add network

packages/extension/e2e/apis/sendDevnetEthToAccount.ts, packages/extension/src/ui/features/accountTokens/SendTokenScreen.tsx, packages/extension/src/ui/features/accountTokens/TokenListItem.tsx, packages/extension/src/ui/features/accountTokens/TokenScreen.tsx, packages/extension/src/ui/features/accountTokens/tokens.state.ts, packages/extension/src/ui/features/accountTokens/useMaxFeeForTransfer.ts, packages/extension/src/ui/features/actions/FeeEstimation.tsx, packages/extension/src/ui/services/backgroundTransactions.ts, scripts/devnet-upgrade-helper.ts
Updates to fix an issue with clicking MAX not enabling the 'Next' button, and slow network conditions allowing a stale balance to be captured in tests.
=> fix: e2e tests

packages/extension/src/shared/network/defaults.ts
=> chore: rename "Ethereum Mainnet“ to “Mainnet“

packages/extension/src/ui/features/accountActivity/ui/ExpandableFieldGroup.tsx, packages/storybook/src/features/accounts/TransactionDetailRaw.stories.tsx
fix: don't show disclosure / hover if there are no children
=> fix(ui): expand arrow

packages/extension/src/ui/components/InputText.tsx, packages/extension/src/ui/components/utils/isAllowedAddressHexInputValue.tsx, packages/extension/src/ui/components/utils/isAllowedNumericInputValue.tsx, packages/extension/test/InputText.test.ts, packages/storybook/src/ui/components/InputText.stories.tsx, packages/storybook/src/ui/components/InputTextArea.stories.tsx
Adds a check for deletion so user can recover from invalid value. Adds stories.
=> fix(ui): always allow delete in input fields

packages/extension/src/ui/features/accountActivity/transform/explorerTransaction/transformers/defaultDisplayNameTransformer.ts
Renames 'Unknown' to 'Contract interaction'
=> chore: rename 'unknown'

packages/extension/src/ui/features/accountTokens/TokenListItem.tsx, packages/storybook/src/features/accountTokens/TokenListItem.stories.tsx
=> fix: gracefully handle very long token names and balance

packages/extension/src/shared/call/erc20ApproveCall.ts, packages/extension/src/shared/call/erc20MintCall.ts, packages/extension/src/shared/call/erc20TransferCall.ts, packages/extension/src/shared/call/erc721TransferCall.ts, packages/extension/src/ui/features/actions/transaction/ERC20ApproveTransactionDetails.tsx, packages/extension/src/ui/features/actions/transaction/TransactionDetails.tsx
Show token and value of ERC20 approve and transfers in transaction review
=> feat: transaction review value

packages/extension/src/shared/call/erc20Call.ts, packages/extension/src/shared/token/price.ts, packages/extension/src/ui/features/accountActivity/TransactionDetail.tsx, packages/extension/src/ui/features/accountActivity/TransactionListItem.tsx, packages/extension/src/ui/features/accountActivity/transform/explorerTransaction/__test__/__fixtures__/explorer-transactions/goerli-alpha/erc20-approve-unlimited.json, packages/extension/src/ui/features/accountActivity/transform/explorerTransaction/__test__/__fixtures__/explorer-transactions/goerli-alpha/erc20-approve.json, packages/extension/src/ui/features/accountActivity/transform/explorerTransaction/__test__/__fixtures__/explorer-transactions/goerli-alpha/index.ts, packages/extension/src/ui/features/accountActivity/transform/explorerTransaction/__test__/fingerprintExplorerTransaction.test.ts, packages/extension/src/ui/features/accountActivity/transform/explorerTransaction/__test__/transformExplorerTransaction.test.ts, packages/extension/src/ui/features/accountActivity/transform/explorerTransaction/fingerprintExplorerTransaction.ts, packages/extension/src/ui/features/accountActivity/transform/explorerTransaction/transformExplorerTransaction.ts, packages/extension/src/ui/features/accountActivity/transform/explorerTransaction/transformers/defaultDisplayNameTransformer.ts, packages/extension/src/ui/features/accountActivity/transform/explorerTransaction/transformers/postTransferTransformer.ts, packages/extension/src/ui/features/accountActivity/transform/explorerTransaction/transformers/tokenApproveTransformer.ts, packages/extension/src/ui/features/accountActivity/transform/is.ts, packages/extension/src/ui/features/accountActivity/transform/type.ts, packages/extension/src/ui/features/accountActivity/ui/TransactionIcon.tsx, packages/extension/src/ui/features/accountActivity/ui/TransferAccessory.tsx, packages/extension/src/ui/features/accountTokens/useDisplayTokenAmountAndCurrencyValue.tsx, packages/extension/src/ui/features/actions/transaction/ERC20TransferTransactionDetails.tsx, packages/extension/test/tokenPrice.test.ts, packages/storybook/src/features/accounts/TransactionDetailExplorer.stories.tsx, packages/storybook/src/features/accounts/TransactionListItem.stories.tsx
Improves display of single 'Approve' transactions and handles special case where approval is unlimited
Transaction review after
Transaction review before
=> feat: parse erc20 approve

packages/extension/src/ui/features/accountActivity/transform/explorerTransaction/__test__/transformExplorerTransaction.test.ts
Fixes a test snapshot that changed as a side effect of two recent merges
=> fix: update test snapshot

Deployment.md
Reverts argentlabs/argent-x#1295 unintentional merge into main, should have been develop
=> Revert "chore: update release steps"

packages/extension/src/ui/features/recovery/RecoverySetupScreen.tsx, packages/storybook/src/features/recovery/RecoverySetupScreen.stories.tsx
=> feat: change text

packages/extension/src/ui/features/recovery/recovery.service.ts, yarn.lock
Fixes by selecting the first unhidden account if the user dismisses extension without selecting account from AccountListScreen
=> fix: hidden account access

packages/extension/src/ui/features/accountTokens/AccountTokens.tsx, packages/extension/src/ui/features/accounts/AccountListScreenItem.tsx
10 secs as placeholder, let's define a better timeout
=> chore: reduce network requests related to accounts

packages/ui/src/components/ScrollContainer.tsx, packages/ui/src/theme/scrollbarStyle.ts
This PR fixes issues with scrolling in FireFox
=> fix: FireFox scrolling workarounds

packages/extension/src/ui/features/accounts/AccountListScreenItem.tsx, packages/extension/src/ui/features/settings/SettingsScreen.tsx
https://user-images.githubusercontent.com/7635032/203052001-631878be-5e1f-4785-87e2-6b1bc0bab944.mov
=> chore: update account click on settings page

packages/extension/src/ui/components/CustomButtonCell.tsx, packages/extension/src/ui/features/accountActivity/AccountActivity.tsx, packages/extension/src/ui/features/accountActivity/AccountActivityContainer.tsx, packages/extension/src/ui/features/accountActivity/PendingTransactions.tsx, packages/extension/src/ui/features/accountActivity/TransactionListItem.tsx, packages/extension/src/ui/features/accountActivity/TransactionsListWrapper.tsx, packages/extension/src/ui/features/accountTokens/TokenListItem.tsx, packages/extension/src/ui/features/accounts/AccountListItem.tsx, packages/extension/src/ui/features/accounts/AccountScreen.tsx, packages/storybook/src/features/accounts/AccountActivity.stories.tsx, packages/storybook/src/ui/components/CellStack.stories.tsx, packages/ui/src/components/Alert.tsx, packages/ui/src/components/CellStack.tsx
This PR is an initial refactor before modifying the activity UI completely. This refactors common components used in account, token list and activity screens. A follow-up PR will update the activity UI in the cells.
=> feat: refactor shared custom button cell

packages/extension/src/background/accountMessaging.ts, packages/extension/src/background/actionMessaging.ts, packages/extension/src/background/index.ts, packages/extension/src/inpage/index.ts, packages/extension/src/inpage/starknetWindowObject.ts, packages/extension/src/shared/messages/AccountMessage.ts
=> fix: notify dapp about account change

packages/extension/src/ui/features/accounts/AccountListItem.tsx, packages/extension/src/ui/features/accounts/AccountListScreenItem.tsx, packages/extension/src/ui/features/accounts/DeprecatedAccountsWarning.tsx, packages/extension/src/ui/features/actions/connectDapp/ConnectDappScreen.tsx, packages/storybook/src/features/accounts/AccountListItem.stories.tsx
Updates the upgrade and connected states of account list items
After
Before
=> BLO-598 - update account list UI

packages/extension/src/shared/avatarImage.ts, packages/extension/test/avatarImage.test.ts
Fixes an issue where deleting the account name while editing caused an exception
=> fix: graceful handling of empty account name

packages/extension/src/ui/features/settings/DeveloperSettings/DeploySmartContractForm.tsx, packages/extension/src/ui/features/settings/DeveloperSettings/DeploySmartContractParameters.tsx
https://user-images.githubusercontent.com/6831124/209346651-e37a5107-e225-4411-8570-f0c50c7f9840.mp4
=> feat: allow felt array for contract deployment

package.json
Reverts argentlabs/argent-x#1636
=> Revert "fix: update bundlesize for current code size"

packages/dapp/package.json, packages/dapp/src/components/TokenDapp.tsx, packages/dapp/src/services/wallet.service.ts, packages/extension/src/background/actionHandlers.ts, packages/extension/src/background/index.ts, packages/extension/src/background/transactions/transactionMessaging.ts, packages/extension/src/background/udcAction.ts, packages/extension/src/background/udcMessaging.ts, packages/extension/src/inpage/ArgentXAccount.ts, packages/extension/src/shared/messages/UdcMessage.ts, packages/extension/src/shared/udc/type.ts
Starkware wants to build some playground like remix ide and need to be able to declare from the wallet through the dapp api.
- implement account.declare for dapps to use
=> feat: expose declare api to dapps

packages/extension/src/ui/AppRoutes.tsx, packages/extension/src/ui/app.state.ts
Improve UI sync when multiple tabs are open
- add event handler
=> chore: sync

packages/extension/src/shared/utils/booleanifyEnv.ts, packages/extension/src/ui/features/accounts/AddNewAccountScreen.tsx
Fixes feature flag in NewAccountScreen
=> fix: multisig feature flag

packages/extension/src/ui/features/lock/PasswordForm.tsx
`Small bug fix where the error thrown from the background is not handled in the UI`
https://argent.atlassian.net/jira/software/c/projects/BLO/boards/20?modal=detail&selectedIssue=BLO-658
=> [BLO-658] add error message on invalid password

packages/extension/src/shared/shield/backend/account.ts, packages/guardian/src/services/CosignerTypes.ts, packages/guardian/src/services/GuardianSigner.ts
Co-signer support for starknet signed typed data
Offchain signatures impl added to GuardiaSigner
=> feat: offchain signature in GuardianSigner

.github/workflows/test.yml
=> chrore: fix pipeline

packages/extension/src/ui/features/shield/escape/EscapeBanner.tsx
=> fix: typo interpolation quotes

packages/extension/src/background/wallet.ts
`This is resolving issue BLO-715, before that all the tickets were only raising the bug itself this is resolving the bug.`
=> [BLO-715] Follow up: replace the error being thrown by a bug fix

packages/extension/src/shared/analytics.ts, packages/extension/src/ui/features/actions/ActionScreen.tsx
`Context: we want to have more insights into user behaviour with dapps, so so we track more events in order to have a funnel or where they leave the flow`
`Added a new event and updated two existing ones`
=> [BLO-721] add analytics for dapp funnel

.github/workflows/test.yml
`Use BE var when build extension for testing`
ie:
- add new ui
=> chore: add env vars for test workflow

packages/extension/e2e/src/languages/ILanguage.ts, packages/extension/e2e/src/languages/en/index.ts, packages/extension/e2e/src/page-objects/ExtensionPage.ts, packages/extension/e2e/src/page-objects/Navigation.ts, packages/extension/e2e/src/specs/accountSettings.spec.ts, packages/extension/e2e/src/specs/recovery.spec.ts, packages/extension/e2e/src/specs/sendFunds.spec.ts
`Add test: user should be able to unlock wallet using password`
ie:
- add new ui
=> test: user should be able to unlock account using password

.gitignore, license-report-config.json, scripts/license-report.sh
Adds a script which can generate a license report.
=> feat(script): license report

packages/extension/src/ui/features/accountNfts/aspect.model.ts
`Fixes a bug report by Ionel where valid NFTs would not go through validation`
=> [BLO-783] fix zod schema

packages/extension/src/ui/features/shield/ShieldBaseOTPScreen.tsx
`Improve error message to make it more user friendly`
=> [BLO-762] improve error message

packages/extension/src/ui/features/accountNfts/aspect.service.ts, packages/extension/src/ui/features/actions/transaction/ApproveTransactionScreen/BalanceChangeOverview/NftDetails.tsx, packages/extension/src/ui/features/actions/transaction/ApproveTransactionScreen/BalanceChangeOverview/index.tsx, packages/extension/src/ui/features/actions/transaction/useTransactionSimulatedData.ts
Adds a fallback for nfts which are not known to aspect
=> feat: fallback for unknown nfts

packages/extension/src/ui/features/actions/transaction/ApproveTransactionScreen/BalanceChangeOverview/index.tsx
=> fix: wording estimate box

packages/extension/src/shared/token/price.ts, packages/extension/src/ui/features/actions/transaction/ApproveTransactionScreen/BalanceChangeOverview/index.tsx
https://argent.atlassian.net/browse/BLO-811
=> feat: show unlimited approval in red

packages/extension/src/ui/features/actions/transaction/ApproveTransactionScreen/BalanceChangeOverview/index.tsx, packages/extension/src/ui/features/actions/transaction/ApproveTransactionScreen/index.tsx, packages/extension/src/ui/features/actions/transaction/useTransactionSimulatedData.ts, yarn.lock
`This is a quick fix for a new release candidate, clearly this would require more work to be done properly`
`Add to make the hook a bit more generic to cover the cases without transfers`
=> [BLO-807] Bug fix for release

packages/extension/src/shared/transactionReview.service.ts, packages/extension/src/ui/features/actions/transaction/ApproveTransactionScreen/BalanceChangeOverview/index.tsx, packages/extension/src/ui/features/actions/transaction/ApproveTransactionScreen/DappHeader/TransactionIcon/SwapTransactionIcon.tsx, packages/extension/src/ui/features/actions/transaction/ApproveTransactionScreen/DappHeader/TransactionIcon/index.test.tsx, packages/extension/src/ui/features/actions/transaction/ApproveTransactionScreen/DappHeader/TransactionIcon/index.tsx, packages/extension/src/ui/features/actions/transaction/useTransactionSimulatedData.ts
Fixes bug related to Transfers and Approvals on Signing Screen
=> Blo 814 warning message shown when user transfer nft to another account

packages/extension/src/ui/features/accountNfts/CollectionNfts.tsx, packages/extension/src/ui/features/accountNfts/NftItem.tsx, packages/extension/src/ui/features/accountNfts/NftScreen.tsx, packages/extension/src/ui/features/accountNfts/aspect.model.ts
https://user-images.githubusercontent.com/50968441/220322237-6c7bdad2-1354-4b81-9ff0-a147ac9e7201.mov
=> fix: allow nullable floorPrice, imageUri and description

packages/extension/src/shared/explorer/type.ts, packages/extension/src/ui/features/accountActivity/TransactionDetail.tsx, packages/extension/src/ui/features/accountActivity/transform/explorerTransaction/dappExplorerTransaction.ts, packages/extension/src/ui/features/accountActivity/transform/explorerTransaction/transformers/dappAlphaRoadSwapTransformer.ts, packages/extension/src/ui/features/accountActivity/transform/explorerTransaction/transformers/dappAspectBuyNFTTransformer.ts, packages/extension/src/ui/features/accountActivity/transform/explorerTransaction/transformers/dappInfluenceMintTransformer.ts, packages/extension/src/ui/features/accountActivity/transform/explorerTransaction/transformers/dappJediswapSwapTransformer.ts, packages/extension/src/ui/features/accountActivity/transform/explorerTransaction/transformers/dappMintSquareBuyNFTTransformer.ts, packages/extension/src/ui/features/accountActivity/transform/explorerTransaction/transformers/dappMySwapSwapTransformer.ts, packages/extension/src/ui/features/accountActivity/transform/explorerTransaction/transformers/knownNftTransformer.ts, packages/extension/src/ui/features/accountActivity/transform/explorerTransaction/transformers/tokenTransferTransformer.ts, packages/storybook/src/features/accounts/TransactionListItem.stories.tsx
Please look at the sentry report in the ticket for exact issue
=> fix: null error on Transaction Details - BLO-818

packages/extension/src/ui/features/accountActivity/transform/explorerTransaction/transformers/knownNftTransformer.ts
=> fix: nft transfer display

packages/extension/src/ui/features/actions/transaction/ApproveTransactionScreen/DappHeader/TransactionTitle.tsx
If the NFT is unknown, which the case on mint, show "Confirm Transaction" fallback
=> fix: TransactionTitle for Unknown NFTs

packages/extension/src/ui/features/actions/connectDapp/useDappDisplayAttributes.ts
=> BLO-800 feat: remove extraction

packages/extension/src/ui/features/accounts/AccountListItem.tsx, packages/extension/src/ui/features/accounts/AccountListScreenItem.tsx
`The issue was caused by the fact that one button was inside another button and it created a race condition in some cases despite the stopPropagation`
=> [BLO-749] Cannot access account settings action in extended view

packages/extension/src/shared/account/details/getAndMergeAccountDetails.test.ts, packages/extension/src/shared/explorer/type.ts, packages/extension/src/ui/features/accountActivity/transform/explorerTransaction/__test__/__fixtures__/explorer-transactions/goerli-alpha/erc20-approve-unlimited.json, packages/extension/src/ui/features/accountActivity/transform/explorerTransaction/__test__/__fixtures__/explorer-transactions/goerli-alpha/erc20-approve.json, packages/extension/src/ui/features/accountActivity/transform/explorerTransaction/__test__/__fixtures__/explorer-transactions/goerli-alpha/erc20-mint-test-token.json, packages/extension/src/ui/features/accountActivity/transform/explorerTransaction/__test__/__fixtures__/explorer-transactions/goerli-alpha/erc20-swap-alpha-road.json, packages/extension/src/ui/features/accountActivity/transform/explorerTransaction/__test__/__fixtures__/explorer-transactions/goerli-alpha/erc20-swap-jediswap.json, packages/extension/src/ui/features/accountActivity/transform/explorerTransaction/__test__/__fixtures__/explorer-transactions/goerli-alpha/erc20-swap-my-swap.json, packages/extension/src/ui/features/accountActivity/transform/explorerTransaction/__test__/__fixtures__/explorer-transactions/goerli-alpha/erc20-transfer-with-sequencer-event.json, packages/extension/src/ui/features/accountActivity/transform/explorerTransaction/__test__/__fixtures__/explorer-transactions/goerli-alpha/erc20-transfer.json, packages/extension/src/ui/features/accountActivity/transform/explorerTransaction/__test__/__fixtures__/explorer-transactions/goerli-alpha/erc721-mint-aspect.json, packages/extension/src/ui/features/accountActivity/transform/explorerTransaction/__test__/__fixtures__/explorer-transactions/goerli-alpha/erc721-mint-mint-square.json, packages/extension/src/ui/features/accountActivity/transform/explorerTransaction/__test__/__fixtures__/explorer-transactions/goerli-alpha/erc721-transfer.json, packages/extension/src/ui/features/accountActivity/transform/explorerTransaction/__test__/__fixtures__/explorer-transactions/goerli-alpha/novel-dapp-aspect-approve-nft-listing.json, packages/extension/src/ui/features/accountActivity/transform/explorerTransaction/__test__/__fixtures__/explorer-transactions/goerli-alpha/novel-dapp-aspect-buy-nft.json, packages/extension/src/ui/features/accountActivity/transform/explorerTransaction/__test__/__fixtures__/explorer-transactions/goerli-alpha/novel-dapp-briq.json, packages/extension/src/ui/features/accountActivity/transform/explorerTransaction/__test__/__fixtures__/explorer-transactions/goerli-alpha/novel-dapp-influence-crewmate-purchase-nft.json, packages/extension/src/ui/features/accountActivity/transform/explorerTransaction/__test__/__fixtures__/explorer-transactions/goerli-alpha/novel-dapp-mint-square-approve-eth.json, packages/extension/src/ui/features/accountActivity/transform/explorerTransaction/__test__/__fixtures__/explorer-transactions/goerli-alpha/novel-dapp-mint-square-approve-nft-listing.json, packages/extension/src/ui/features/accountActivity/transform/explorerTransaction/__test__/__fixtures__/explorer-transactions/goerli-alpha/novel-dapp-mint-square-buy-nft.json, packages/extension/src/ui/features/accountActivity/transform/explorerTransaction/__test__/__fixtures__/explorer-transactions/goerli-alpha/novel-dapp-no-game.json, packages/extension/src/ui/features/accountActivity/transform/explorerTransaction/__test__/transformExplorerTransaction.test.ts, packages/extension/src/ui/features/accountActivity/transform/transaction/__test__/transformTransaction.test.ts, packages/extension/src/ui/features/accountNfts/aspect.mock.ts, packages/storybook/src/account.ts, packages/storybook/src/features/accounts/TransactionDetailExplorer.stories.tsx, packages/storybook/src/features/accounts/TransactionDetailRaw.stories.tsx, packages/storybook/src/features/accounts/TransactionListItem.stories.tsx, packages/storybook/src/features/accounts/__fixtures__/transactions-pending.json
`Removed user data and replaced with seed data`
=> [BLO-803] removed all occurences of existing wallets

packages/extension/package.json, packages/extension/test/argentApiFetcher.test.ts, packages/extension/test/fetcher.test.ts, packages/extension/tsconfig.json, yarn.lock
`Remove dependency on sub tier library`
This also required to update the few but existing mocks
=> [BLO-734] remove vi-fetch dependency

packages/extension/src/ui/features/networks/NetworkSwitcher.tsx, packages/extension/src/ui/features/swap/Swap.tsx
Network switcher could appear under main content
- adjust UI to use natural dom order instead of z-index
- remove Portal and use natural dom order instead
=> BLO-724 fix: network switcher overlap

.github/workflows/test-e2e.yml, .github/workflows/test.yml
Reverts argentlabs/argent-x#1845
It makes every task run twice on PRs.
=> Revert "feat[CI]: run tests on feature branches"

packages/extension/src/background/index.ts, packages/window/src/types.test.ts
Personal message sign times out
- adjust keypath for message data
- add basic test
=> BOL-869 fix: message sign payload

packages/extension/src/shared/shield/jwt.ts
=> BLO-877 chore: reduce expiry time

packages/extension/src/background/accountMessaging.ts, packages/extension/src/background/wallet.ts, packages/extension/src/shared/messages/AccountMessage.ts, packages/extension/src/ui/services/backgroundAccounts.ts
- picks `getPublicKey` fn from multisig
=> chore: add get public key fn

packages/extension/src/ui/features/accounts/upgrade.service.ts
=> fix: re-enable upgrade screen

packages/extension/src/ui/features/accountNfts/CollectionNfts.tsx
`Adding a fallback icon where it's missing`
=> add fallback icon for missing nft

packages/extension/e2e/src/page-objects/Account.ts, packages/extension/e2e/src/page-objects/Activity.ts, packages/extension/e2e/src/specs/receiveFunds.spec.ts, packages/extension/e2e/src/specs/sendFunds.spec.ts, packages/extension/playwright.config.ts
=> tests: Check activity

lerna.json, packages/extension/manifest/v2.json, packages/extension/manifest/v3.json, packages/extension/package.json, packages/storybook/package.json
=> Backmerge main <- v5.3.10

lerna.json, packages/extension/manifest/v2.json, packages/extension/manifest/v3.json, packages/extension/package.json, packages/extension/src/ui/features/accounts/upgrade.service.ts, packages/storybook/package.json, packages/window/package.json
=> Backmerge develop <- main

.github/workflows/chromatic.yml, .github/workflows/dependabot.yml, .github/workflows/test-e2e.yml, .github/workflows/test.yml
=> chore: Skip chromatic and test build publish

packages/extension/src/ui/features/actions/transaction/ApproveTransactionScreen/DappHeader/index.tsx, packages/extension/src/ui/features/actions/transaction/ApproveTransactionScreen/VerifiedDappBanner/VerifiedDappModal.tsx, packages/extension/src/ui/features/actions/transaction/ApproveTransactionScreen/VerifiedDappBanner/index.tsx, packages/extension/src/ui/features/actions/transaction/ApproveTransactionScreen/index.tsx
Update the UI for verified dapps
- update the UI for verified dapps
=> BLO-858 chore: verified dapp ui

packages/extension/src/ui/features/shield/ShieldAccountOTPScreen.tsx, packages/extension/src/ui/features/shield/ShieldBaseEmailScreen.tsx
See original ticket for scenario
- alway reset when validating a new email address
=> BLO-912 fix: always reset

packages/extension/src/ui/features/actions/transaction/ApproveTransactionScreen/VerifiedDappBanner/VerifiedDappModal.tsx, packages/extension/src/ui/features/shield/escape/EscapeGuardian.tsx, packages/extension/src/ui/features/shield/escape/EscapeSigner.tsx, packages/extension/src/ui/features/shield/ui/ShieldExternalLinkButton.tsx, packages/extension/src/ui/features/shield/ui/ShieldLearnMoreButton.tsx
'Update placeholder links with actual values'
- Update placeholder links with actual values
=> BLO-960 feat: 2fa links

.github/workflows/test-e2e.yml, .github/workflows/test.yml, packages/extension/package.json
Tests were not running on PR's to main, causing issue with bundlesize in release
- run tests on PR's to main
- fix bundlesize by removing duplicate dependency with mismatching version
=> fix: bundlesize, run test on main pr's

lerna.json, packages/dapp/package.json, packages/extension/manifest/v2.json, packages/extension/manifest/v3.json, packages/extension/package.json, packages/get-starknet/package.json, packages/guardian/package.json, packages/multicall/package.json, packages/sessions/package.json, packages/stack-router/package.json, packages/storybook/package.json, packages/swap/package.json, packages/ui/package.json, packages/window/package.json
=> backmerge main <- v5.3.12

.github/workflows/dependabot.yml
=> fix: dependabot flow

lerna.json, packages/dapp/package.json, packages/extension/manifest/v2.json, packages/extension/manifest/v3.json, packages/extension/package.json, packages/get-starknet/package.json, packages/guardian/package.json, packages/multicall/package.json, packages/sessions/package.json, packages/stack-router/package.json, packages/storybook/package.json, packages/swap/package.json, packages/ui/package.json, packages/window/package.json
=> backmerge main <- v5.3.13

lerna.json, packages/dapp/package.json, packages/extension/manifest/v2.json, packages/extension/manifest/v3.json, packages/extension/package.json, packages/get-starknet/package.json, packages/guardian/package.json, packages/multicall/package.json, packages/sessions/package.json, packages/stack-router/package.json, packages/storybook/package.json, packages/swap/package.json, packages/ui/package.json, packages/window/package.json
=> backmerge main <- v5.3.14

packages/extension/src/ui/features/actions/feeEstimation/CombinedFeeEstimation.tsx, packages/extension/src/ui/features/actions/feeEstimation/FeeEstimation.tsx, packages/extension/src/ui/features/actions/feeEstimation/ui/FeeEstimationBox.tsx, packages/extension/src/ui/features/actions/transaction/ApproveTransactionScreen/BalanceChangeOverview/index.tsx, packages/extension/src/ui/features/actions/transaction/ApproveTransactionScreen/index.tsx, packages/storybook/src/features/actions/transaction/CombinedFeeEstimation.stories.tsx, packages/storybook/src/features/actions/transaction/FeeEstimation.stories.tsx, packages/storybook/src/features/actions/transaction/FeeEstimationBox.stories.tsx, packages/storybook/src/features/actions/transaction/__fixtures__/fees/combinedFeeEstimationFixtures.ts, packages/storybook/src/features/actions/transaction/__fixtures__/fees/feeEstimationFixtures.ts, packages/storybook/src/tokensByNetwork.ts
Make fee box UI match designs. Merges onto #1925 
- refactor fee components
- capture test fixtures
- add storybooks
=> BLO-913 fix: fee UI

packages/extension/e2e/Dockerfile
=> fix: pin devnet

packages/extension/src/background/transactions/transactionExecution.ts, packages/extension/src/background/transactions/transactionMessaging.ts, packages/extension/src/shared/call/addMultisigSignersCall.ts, packages/extension/src/shared/call/setMultisigThresholdCalls.ts, packages/extension/src/shared/messages/TransactionMessage.ts, packages/extension/src/shared/multisig/account.ts, packages/extension/src/shared/multisig/multisig.model.ts, packages/extension/src/shared/multisig/multisig.service.ts, packages/extension/src/shared/multisig/pendingTransactionsStore.ts, packages/extension/src/shared/transactions.ts, packages/extension/src/shared/utils/starknetNetwork.ts, packages/extension/src/ui/features/accountActivity/AccountActivityContainer.tsx, packages/extension/src/ui/features/accountActivity/PendingMultisigTransactions.tsx, packages/extension/src/ui/features/accountActivity/TransactionListItem.tsx, packages/extension/src/ui/features/accountActivity/transform/transaction/transformTransaction.ts, packages/extension/src/ui/features/accountActivity/transform/transaction/transformers/addMultisigTransformer.ts, packages/extension/src/ui/features/accountActivity/transform/transaction/transformers/changeMultisigThresholdTransformer.ts, packages/extension/src/ui/features/accountActivity/transform/transaction/transformers/pendingMultisigTransactionAdapter.ts, packages/extension/src/ui/features/accountActivity/transform/type.ts, packages/extension/src/ui/features/accountActivity/ui/TransactionIcon.tsx, packages/extension/src/ui/features/actions/transaction/ApproveTransactionScreen/ConfirmScreen.tsx, packages/extension/src/ui/features/actions/transaction/ApproveTransactionScreen/index.tsx, packages/extension/src/ui/features/multisig/MultisigConfirmationsScreen.tsx, packages/extension/src/ui/features/multisig/SetConfirmationsInput.tsx, packages/extension/src/ui/features/multisig/multisigTransactions.state.ts
`Implemented transformers for multisig transactions`
- Add transformer for changeThreshold and addSigners transactions
- Create store to store pending multisig transactions
- Sync pending transactions with backend, if no longer awaiting one or more signature the transaction should not longer be stored with pendingMultisigTransactions
=> [BLO-700] Transaction transformers for Multisig

lerna.json, packages/dapp/package.json, packages/extension/manifest/v2.json, packages/extension/manifest/v3.json, packages/extension/package.json, packages/get-starknet/package.json, packages/guardian/package.json, packages/multicall/package.json, packages/sessions/package.json, packages/stack-router/package.json, packages/storybook/package.json, packages/swap/package.json, packages/ui/package.json, packages/window/package.json
=> Merge main into develop (v5.3.16)

packages/extension/e2e/src/languages/ILanguage.ts, packages/extension/e2e/src/languages/en/index.ts, packages/extension/e2e/src/page-objects/Settings.ts, packages/extension/e2e/src/page-objects/Wallet.ts, packages/extension/e2e/src/specs/links.spec.ts, packages/extension/src/ui/components/PrivacyStatementText.tsx
Add tests:
- Check privacy statement (onboarding and settings)
- Check help links
=> test: check privacy statement and help links

packages/extension/src/shared/token/storage.ts, packages/extension/src/shared/token/type.ts, packages/extension/src/ui/features/actions/AddTokenScreen.tsx
There was issue adding tokens with Symbol length > 6. Now we have switched to using zod instead of yup and allowing any length of Symbol length
- Replace yup with zod
- Allow symbol length > 6
=> feat: use zod token schema

packages/extension/src/shared/shield/backend/time.ts
=> Simplify backend time sync

packages/extension/src/shared/shield/jwt.ts
=> Fix JWT expiration time
